version: '3.8'

services: 
  database:
    container_name: db_api_levietnamien
    image: mysql:8.0
    environment: 
      MYSQL_ROOT_PASSWORD: motdepasse
      MYSQL_DATABASE: symfony_docker
    ports: 
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib.mysql

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '5518:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
